answers/urls.py
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import path

from hunts.views import LastAccessedHuntRedirectView

from .views import AnswerView, answers, update_note

app_name = "answers"
urlpatterns = [
    path("queue/<slug:hunt_slug>", AnswerView.as_view(), name="submission_queue"),
    path("queue/<slug:hunt_slug>/answers", answers),
    path("queue/<slug:hunt_slug>/<int:answer_pk>", AnswerView.as_view()),
    path("update_note/<int:answer_pk>", update_note, name="update_note"),
    path(
        "",
        LastAccessedHuntRedirectView.as_view(pattern_name="answers:submission_queue"),
        name="queue",
    ),
]

api/urls.py
from django.urls import path

from . import views

hunt_detail = views.HuntViewSet.as_view(
    {
        "get": "retrieve",
    }
)

puzzle_list = views.PuzzleViewSet.as_view(
    {
        "get": "list",
        "post": "create",
    }
)

puzzle_detail = views.PuzzleViewSet.as_view(
    {
        "get": "retrieve",
        "delete": "destroy",
        "patch": "partial_update",
    }
)

answer_list = views.AnswerViewSet.as_view(
    {
        "post": "create",
    }
)

answer_detail = views.AnswerViewSet.as_view(
    {
        "delete": "destroy",
        "patch": "partial_update",
    }
)

tag_list = views.PuzzleTagViewSet.as_view(
    {
        "post": "create",
    }
)

notes_detail = views.PuzzleNotesView.as_view(
    {
        "post": "update",
    }
)

tag_detail = views.PuzzleTagViewSet.as_view(
    {
        "get": "retrieve",
        "delete": "destroy",
    }
)

urlpatterns = [
    path("v1/hunts/<int:pk>", hunt_detail, name="hunt_detail"),
    path("v1/hunts/<int:hunt_id>/puzzles", puzzle_list, name="puzzle_list"),
    path(
        "v1/hunts/<int:hunt_id>/puzzles/<int:pk>", puzzle_detail, name="puzzle_detail"
    ),
    path(
        "v1/puzzles/<int:puzzle_id>/answers",
        answer_list,
        name="answer_list",
    ),
    path(
        "v1/puzzles/<int:puzzle_id>/answers/<int:pk>",
        answer_detail,
        name="answer_detail",
    ),
    path("v1/puzzles/<int:puzzle_id>/notes", notes_detail, name="notes_detail"),
    path("v1/puzzles/<int:puzzle_id>/tags", tag_list, name="tag_list"),
    path(
        "v1/puzzles/<int:puzzle_id>/tags/<int:pk>",
        tag_detail,
        name="tag_detail",
    ),
]

cardboard/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("hunts/", include("hunts.urls")),
    path("answers/", include("answers.urls")),
    path("api/", include("api.urls")),
    path("puzzles/", include("puzzles.urls")),
    path("tools", views.tools, name="tools"),
    path("privacy", views.privacy, name="privacy"),
    path("", views.home, name="home"),
    path("", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += [
        path("silk/", include("silk.urls", namespace="silk")),
    ]

smallboard/urls.py
from django.conf import settings
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("hunts/", include("hunts.urls")),
    path("answers/", include("answers.urls")),
    path("api/", include("api.urls")),
    path("puzzles/", include("puzzles.urls")),
    path("tools", views.tools, name="tools"),
    path("privacy", views.privacy, name="privacy"),
    path("", views.home, name="home"),
    path("", include("social_django.urls", namespace="social")),
]

smallboard/templates/base-react.html
{% load static %}
<html lang="en">
    <head>
        <title>Cardinality Smallboard</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
        <script src="https://kit.fontawesome.com/cddeb3e966.js" crossorigin="anonymous"></script>
        <script crossorigin src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
        <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">Cardinality</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'tools' %}">Tools and References</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'queue' %}">Answer Queue</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                        <li class="nav-item">
                            <div class="nav-link disabled">Logged in as
                        {% if user.first_name %}
                            {{user.first_name}} {{user.last_name}}
                        {% else %}
                            {{ user.username }}
                        {% endif %}
                        {% if user.email %}
                            ({{user.email}})
                        {% endif %}
                            </div>
                        </li>
                    {% else %}
                    {% if is_google_auth_enabled %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'social:begin' 'google-oauth2' %}">Login</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">Signup</a>
                    </li>
                    {% endif %}
                {% endif %}
                </ul>
            </div>

        </nav>

        <div id='ajax-messages'></div>
        {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger" style="white-space: pre-line" role="alert">{{ message }}</div>
        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            <div class="alert alert-warning" style="white-space: pre-line" role="alert">{{ message }}</div>
        {% endif %}
        {% endfor %}

        {% block page_content %}{% endblock %}
    </body>
</html>

smallboard/templates/base.html
{% load static %}
<html lang="en">
    <head>
        <title>Cardinality Smallboard</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">

        <meta name="google-site-verification" content="Ti5cGx93wum_wEEzeEhSPrfyyhJmrza9sv_1ee25FAY" />

        {% block head_content %}{% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">
                <img height="40" src="{% static 'favicon.ico' %}" alt="">
                Smallboard
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'tools' %}">Tools and References</a>
                        </li>
                        {% if hunt.answer_queue_enabled %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'answers:queue' %}">Answer Queue</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                        <li class="nav-item">
                            <div class="nav-link disabled">Logged in as
                        {% if user.first_name %}
                            {{user.first_name}} {{user.last_name}}
                        {% else %}
                            {{ user.username }}
                        {% endif %}
                        {% if user.email %}
                            ({{user.email}})
                        {% endif %}
                            </div>
                        </li>
                    {% else %}
                    {% if not is_google_auth_enabled %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">Signup</a>
                    </li>
                    {% endif %}
                {% endif %}
                </ul>
            </div>

        </nav>

        <div id='ajax-messages'></div>
        {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger" style="white-space: pre-line" role="alert">{{ message }}</div>
        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            <div class="alert alert-warning" style="white-space: pre-line" role="alert">{{ message }}</div>
        {% endif %}
        {% endfor %}

        {% block page_content %}{% endblock %}
    </body>

    <footer class="footer">
        <div class="container">
            <p class="small text-muted">By using our site, you acknowledge that you have read and understand our <a href="{% url 'privacy'%}">Privacy Policy</a></p>
        </div>
    </footer>
</html>

smallboard/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}


<div class="container">
    <div class="row">
        <div class="col-sm">

            <h1>Cardinality Smallboard</h1>


            <ul>
                <li>
                    <b>What is this?</b><br>
                    A dashboard for managing puzzles and tracking status during a puzzle hunt, such as MIT Mystery Hunt:

                    <img class="img-fluid" src="{% static 'dashboard.png' %}">
                </li>
                <li>
                    <b>Why do I have to sign in?</b><br>
                    We use Google login to ensure that users only see puzzles for the hunts they are participating in.
                </li>
                <li>
                    <b>How are you using my data?</b><br>
                    We match your email against a whitelist of emails for each hunt. The actions you take while using the smallboard (such as solving a puzzle) may be logged and attributed to your email. This data is only used for logging purposes. See <a href="{% url 'privacy'%}">here</a> for our full privacy policy.
                </li>

                <li>
                    <b>Cool. Why does it say "Your credentials aren't allowed" when I try to sign in?</b> <br>
                    You are currently not whitelisted for any active hunts. If you believe you should have access or would like to be whitelisted for a hunt, please email <a href="mailto:cardinalitypuzzles@gmail.com">cardinalitypuzzles@gmail.com</a>.
                </li>

            </ul>

            {% if is_google_auth_enabled %}
                <a href="{% url 'social:begin' 'google-oauth2' %}"><img src="{% static 'signin.png' %}" alt="Login with Google" ></a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'login' %}">Log in</a>
                <a class="btn btn-primary" href="{% url 'signup' %}">Sign Up</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}